server:
  port: 8080
spring:
  config:
    import:
      - nacos:nacos-config-example.properties?refreshEnabled=true
      - nacos:springAiDemo.yml?refreshEnabled=true
  application:
    name: springAiDemo
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/spring_ai_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: ${CHAT_MODEL:qwen-plus}
          max-tokens: ${MAX_TOKEN:300}
      embedding:
        options:
          model: ${EMBEDDING_MODEL:text-embedding-v3}
      base-url: ${DASHSCOPE_BASE_URL:https://dashscope.aliyuncs.com}
    vectorstore:
      milvus:
        client:
          host: ${HOST}
          port: ${MILVUS_PORT}
        database-name: springAiDemo
        collectionName: springAiDemo
        indexType: IVF_FLAT
        embeddingDimension: 1024
        initialize-schema: true
    memory:
      redis:
        host: ${HOST}
        port: ${REDIS_PORT}
        password: ${REDIS_PASSWORD}
        timeout: 2000
      mysql:
        jdbc-url: ${DB_URL:jdbc:mysql://localhost:3306/spring_ai_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD}
        enabled: true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml
    compatibility-verifier:
      enabled: false
logging:
  level:
    org.springframework.ai.chat.client: debug
    com.touhouqing.springaidemo: debug